### ISSUE TITLE
Help with code

### ISSUE THREAD

**Issue by sam-tj** [thaanstad/ESP32_CanOpenNode#2]
Hi @thaanstad ,

Great work with the library. 

I have a couple of questions. I can see that the code is documented, but as mentioned in the start that pdo, sdo, and  nmt are configured. But is it configured using the **object dictionary file (eds).**  or using the code.

**Comment by thaanstad** [comment]
The PDO and SDOs are configured via the CANopenEditor: https://github.com/CANopenNode/CANopenEditor

The NMT was operational from within CANOpenNode

This video is very helpful although it is for the STM32:  https://www.youtube.com/watch?v=R-r5qIOTjOo

I would note that I had issues with specific versions of the CANOpenEditor.  I therefore was explicit with the version of this software that I checked out: 76baf61845d0dfeb26f36e7db8a07f2cc0f3d30b

**Comment by sam-tj** [comment]
Thanks for the reply.

What was the error that you faced if I may ask?

Additionally, is it possible to use external OD.h without modifying your files? I plan to use it with platform io. Hence keep your stuff intact and use mine. 

Thanks again for your hard work. :)

**Comment by thaanstad** [comment]
The other versions of the CANOpenEditor generated OD.h and OD.cpp files that wouldn't compile correctly.  It appeared that they didn't match up with the version of CanOpenNode that I was using.

My understanding of CANOpenNode is that the OD.h and OD.cpp should be generated using CanOpenEditor.  You should be able to generate these files and replace them in the library.  The library includes an xpd file which you can use as a starting point if you like.

**Comment by thaanstad** [comment]
@sam-tj  Here is a copy of the platformio.ini file I am using with this library:

```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
#lib_deps = C:\Arduino\arduino-1.8.13\portable\sketchbook\libraries\FiniteStateMachine\
     

lib_extra_dirs = 
    C:\Arduino\arduino-1.8.19\portable\sketchbook\libraries\ESP32_CanOpenNode\
    C:\Arduino\arduino-1.8.19\portable\sketchbook\libraries\CanController\


debug_tool = olimex-arm-usb-tiny-h

board_build.partitions = min_spiffs.csv
board_build.flash_mode = qio

;build_unflags = 
;    -Og
build_flags =
    -DCORE_DEBUG_LEVEL=5
    -DBOARD_HAS_PSRAM
    -DCONFIG_ARDUHAL_LOG_COLORS=1
    -mfix-esp32-psram-cache-issue
    -DCONFIG_MBEDTLS_DYNAMIC_BUFFER=1
    -DCONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST=1
    -DCONFIG_SPIRAM_CACHE_WORKAROUND=1
    -O0 
    -ggdb3 
    -g3
    
upload_port = COM[3]
monitor_port = COM[3]
monitor_speed = 1000000
;monitor_filters = direct
monitor_rts = 1
monitor_filters = esp32_exception_decoder
;build_type = debug
```

**Comment by sam-tj** [comment]
Great thanks. 

I used the latest release of the editor and the code compiled and works. I didn't find any bugs or errors until now. ( CANopenEditor v4.1-30-g5935269 )

Maybe for now I will replace the OD files in the library only. 

Let's see if Canopennode devs reply.

Thanks for this.
